## This configuration was generated by terraform-provider-oci

data oci_identity_availability_domain export_nymc-US-ASHBURN-AD-1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  ad_number      = "1"
}
data oci_identity_availability_domain export_nymc-US-ASHBURN-AD-2 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  ad_number      = "2"
}
data oci_identity_availability_domain export_nymc-US-ASHBURN-AD-3 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  ad_number      = "3"
}
resource oci_file_storage_file_system export_csi-fss-7c01a0de-bc7e-460f-a4a2-4d8ebf3b70b9 {
  availability_domain = var.availability_domain--nymc-US-ASHBURN-AD-1
  clone_attach_status = "DETACHED"
  compartment_id      = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = oci_containerengine_cluster.export_hml-oke-02.id
    "Oracle-Tags.CreatedOn" = "2023-10-23T01:22:12.959Z"
  }
  #detach_clone_trigger = <<Optional value not found in discovery>>
  display_name                  = "csi-fss-7c01a0de-bc7e-460f-a4a2-4d8ebf3b70b9"
  filesystem_snapshot_policy_id = ""
  freeform_tags = {
    "exportSetId"         = "ocid1.exportset.oc1.iad.aaaaacvippzulxd7nfqwillqojxwiotjmfsc2ylefuzaaaaa"
    "isDeleteMountTarget" = "false"
    "mountTargetOCID"     = oci_file_storage_mount_target.export_MountTarget-efs-mc-shared.id
  }
  kms_key_id = ""
  #source_snapshot_id = <<Optional value not found in discovery>>
}

resource oci_file_storage_file_system export_csi-fss-d0e1a261-08bc-4f34-aab5-c25d8447b8eb {
  availability_domain = var.availability_domain--nymc-US-ASHBURN-AD-1
  clone_attach_status = "DETACHED"
  compartment_id      = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = oci_containerengine_cluster.export_hml-oke-02.id
    "Oracle-Tags.CreatedOn" = "2023-10-23T01:20:33.054Z"
  }
  #detach_clone_trigger = <<Optional value not found in discovery>>
  display_name                  = "csi-fss-d0e1a261-08bc-4f34-aab5-c25d8447b8eb"
  filesystem_snapshot_policy_id = ""
  freeform_tags = {
    "exportSetId"         = "ocid1.exportset.oc1.iad.aaaaacvippzulxd7nfqwillqojxwiotjmfsc2ylefuzaaaaa"
    "isDeleteMountTarget" = "false"
    "mountTargetOCID"     = oci_file_storage_mount_target.export_MountTarget-efs-mc-shared.id
  }
  kms_key_id = ""
  #source_snapshot_id = <<Optional value not found in discovery>>
}

resource oci_file_storage_file_system export_nfs-efs-mc-shared-sandbox {
  availability_domain = var.availability_domain--nymc-US-ASHBURN-AD-1
  clone_attach_status = "DETACHED"
  compartment_id      = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-15T20:03:11.435Z"
  }
  #detach_clone_trigger = <<Optional value not found in discovery>>
  display_name                  = "nfs-efs-mc-shared-sandbox"
  filesystem_snapshot_policy_id = ""
  freeform_tags = {
  }
  kms_key_id = ""
  #source_snapshot_id = <<Optional value not found in discovery>>
}

resource oci_file_storage_mount_target export_MountTarget-efs-mc-shared {
  availability_domain = var.availability_domain--nymc-US-ASHBURN-AD-1
  compartment_id      = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-15T20:03:13.808Z"
  }
  display_name = "MountTarget-efs-mc-shared"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  idmap_type = "NONE"
  ip_address = "172.28.102.161"
  nsg_ids = [
  ]
  subnet_id = oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_02.id
}

