## This configuration was generated by terraform-provider-oci

resource oci_containerengine_cluster export_hml-oke-02 {
  cluster_pod_network_options {
    cni_type = "OCI_VCN_IP_NATIVE"
  }
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-14T20:48:13.501Z"
  }
  endpoint_config {
    is_public_ip_enabled = "true"
    nsg_ids = [
      oci_core_network_security_group.export_hml-oke-sg-01.id,
    ]
    subnet_id = oci_core_subnet.export_SUB_HML_PUB_ASHBURN_01.id
  }
  freeform_tags = {
  }
  image_policy_config {
    is_policy_enabled = "false"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  kubernetes_version = "v1.27.2"
  name               = "hml-oke-02"
  options {
    add_ons {
      is_kubernetes_dashboard_enabled = "false"
      is_tiller_enabled               = "false"
    }
    admission_controller_options {
      is_pod_security_policy_enabled = "false"
    }
    kubernetes_network_config {
      pods_cidr     = "10.244.0.0/16"
      services_cidr = "10.96.0.0/16"
    }
    persistent_volume_config {
      defined_tags = {
      }
      freeform_tags = {
      }
    }
    service_lb_config {
      defined_tags = {
      }
      freeform_tags = {
      }
    }
    service_lb_subnet_ids = [
      oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_01.id,
    ]
  }
  type   = "ENHANCED_CLUSTER"
  vcn_id = oci_core_vcn.export_VCN_172-28_SANDBOX.id
}

resource oci_containerengine_node_pool export_pool1 {
  cluster_id     = oci_containerengine_cluster.export_hml-oke-02.id
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-14T20:48:16.715Z"
  }
  freeform_tags = {
    "Name" = "hml-oke-02"
  }
  initial_node_labels {
    key   = "name"
    value = "pool1"
  }
  initial_node_labels {
    key   = "spotinst.io/node-lifecycle"
    value = "od"
  }
  initial_node_labels {
    key   = "aplicacao"
    value = "ondemand"
  }
  kubernetes_version = "v1.27.2"
  name               = "pool1"
  node_config_details {
    defined_tags = {
    }
    freeform_tags = {
    }
    is_pv_encryption_in_transit_enabled = "false"
    kms_key_id                          = ""
    node_pool_pod_network_option_details {
      cni_type          = "OCI_VCN_IP_NATIVE"
      max_pods_per_node = "31"
      pod_nsg_ids = [
      ]
      pod_subnet_ids = [
        oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_02.id,
      ]
    }
    nsg_ids = [
    ]
    placement_configs {
      availability_domain = data.oci_identity_availability_domain.export_nymc-US-ASHBURN-AD-1.name
      #capacity_reservation_id = <<Optional value not found in discovery>>
      fault_domains = [
      ]
      #preemptible_node_config = <<Optional value not found in discovery>>
      subnet_id = oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_02.id
    }
    size = "1"
  }
  node_eviction_node_pool_settings {
    eviction_grace_duration              = "PT2M"
    is_force_delete_after_grace_duration = "false"
  }
  node_metadata = {
  }
  node_shape = "VM.Standard.E4.Flex"
  node_shape_config {
    memory_in_gbs = "16"
    ocpus         = "4"
  }
  node_source_details {
    boot_volume_size_in_gbs = "200"
    image_id                = "ocid1.image.oc1.iad.aaaaaaaa7bifibwt6gbfugqbjvfac6vg2wpzgpjk7wxftcgnrp2jejjoanwa"
    source_type             = "IMAGE"
  }
  #quantity_per_subnet = <<Optional value not found in discovery>>
  ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPZ+sr4MDY/TWACA/Ght7A1KaKoquDjhYaZFDof9P+vF6lYYJFLaAeo9DIuszNnKYwG2lsnf7UE7YvtyainWEZ/xKVO9J78peXSsmkZpyJX9s6bAmbiZ+TafhGnGuEWwwMERXOD+KgzRLGC3Gmchf0kiKB1AJroviGNdbGWMmgEyt661oC5QdhCywrXdbIGp0EmkO01HjWbSpMYRT70C+f/8+RvPjbnJaW2sBuIgvow9PHdiblbqEx91fnmK31Y8hHMqRnR5UvrbZ/sLX8T6/T9HEJpWUkAIbmWmBf9R6OVYr0rAg9/sbmsMGju/AkqwjzR5gLqM+incNTPzcauAUD rsa-key-20231013"
  #subnet_ids = <<Optional value not found in discovery>>
}

resource oci_containerengine_node_pool export_pool2 {
  cluster_id     = oci_containerengine_cluster.export_hml-oke-02.id
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-18T19:18:19.692Z"
  }
  freeform_tags = {
  }
  initial_node_labels {
    key   = "name"
    value = "pool2"
  }
  initial_node_labels {
    key   = "spotinst.io/node-lifecycle"
    value = "od"
  }
  initial_node_labels {
    key   = "aplicacao"
    value = "celery"
  }
  kubernetes_version = "v1.27.2"
  name               = "pool2"
  node_config_details {
    defined_tags = {
    }
    freeform_tags = {
    }
    is_pv_encryption_in_transit_enabled = "false"
    kms_key_id                          = ""
    node_pool_pod_network_option_details {
      cni_type          = "OCI_VCN_IP_NATIVE"
      max_pods_per_node = "110"
      pod_nsg_ids = [
      ]
      pod_subnet_ids = [
        oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_03.id,
      ]
    }
    nsg_ids = [
    ]
    placement_configs {
      availability_domain = data.oci_identity_availability_domain.export_nymc-US-ASHBURN-AD-1.name
      #capacity_reservation_id = <<Optional value not found in discovery>>
      fault_domains = [
      ]
      #preemptible_node_config = <<Optional value not found in discovery>>
      subnet_id = oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_03.id
    }
    size = "3"
  }
  node_eviction_node_pool_settings {
    eviction_grace_duration              = "PT2M"
    is_force_delete_after_grace_duration = "false"
  }
  node_metadata = {
    "user_data" = "IyEvYmluL2Jhc2gKY3VybCAtLWZhaWwgLUggIkF1dGhvcml6YXRpb246IEJlYXJlciBPcmFjbGUiIC1MMCBodHRwOi8vMTY5LjI1NC4xNjkuMjU0L29wYy92Mi9pbnN0YW5jZS9tZXRhZGF0YS9va2VfaW5pdF9zY3JpcHQgfCBiYXNlNjQgLS1kZWNvZGUgPi92YXIvcnVuL29rZS1pbml0LnNoCmJhc2ggL3Zhci9ydW4vb2tlLWluaXQuc2gKc3VkbyAvdXNyL2xpYmV4ZWMvb2NpLWdyb3dmcyAteQ=="
  }
  node_pool_cycling_details {
    is_node_cycling_enabled = "true"
    maximum_surge           = "1"
    maximum_unavailable     = "1"
  }
  node_shape = "VM.Standard.E4.Flex"
  node_shape_config {
    memory_in_gbs = "64"
    ocpus         = "8"
  }
  node_source_details {
    boot_volume_size_in_gbs = "150"
    image_id                = "ocid1.image.oc1.iad.aaaaaaaa7bifibwt6gbfugqbjvfac6vg2wpzgpjk7wxftcgnrp2jejjoanwa"
    source_type             = "IMAGE"
  }
  #quantity_per_subnet = <<Optional value not found in discovery>>
  ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPZ+sr4MDY/TWACA/Ght7A1KaKoquDjhYaZFDof9P+vF6lYYJFLaAeo9DIuszNnKYwG2lsnf7UE7YvtyainWEZ/xKVO9J78peXSsmkZpyJX9s6bAmbiZ+TafhGnGuEWwwMERXOD+KgzRLGC3Gmchf0kiKB1AJroviGNdbGWMmgEyt661oC5QdhCywrXdbIGp0EmkO01HjWbSpMYRT70C+f/8+RvPjbnJaW2sBuIgvow9PHdiblbqEx91fnmK31Y8hHMqRnR5UvrbZ/sLX8T6/T9HEJpWUkAIbmWmBf9R6OVYr0rAg9/sbmsMGju/AkqwjzR5gLqM+incNTPzcauAUD rsa-key-20231013"
  #subnet_ids = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_hml-oke-02_addon {
  addon_name                       = "CertManager"
  cluster_id                       = oci_containerengine_cluster.export_hml-oke-02.id
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_hml-oke-02_addon_1 {
  addon_name                       = "CoreDNS"
  cluster_id                       = oci_containerengine_cluster.export_hml-oke-02.id
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_hml-oke-02_addon_2 {
  addon_name                       = "KubeProxy"
  cluster_id                       = oci_containerengine_cluster.export_hml-oke-02.id
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_hml-oke-02_addon_3 {
  addon_name                       = "KubernetesDashboard"
  cluster_id                       = oci_containerengine_cluster.export_hml-oke-02.id
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_hml-oke-02_addon_4 {
  addon_name                       = "OciVcnIpNative"
  cluster_id                       = oci_containerengine_cluster.export_hml-oke-02.id
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

