## This configuration was generated by terraform-provider-oci

resource oci_dns_view export_VCN_172-28_SANDBOX_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-13T15:55:50.701Z"
  }
  display_name = "VCN_172.28_SANDBOX"
  freeform_tags = {
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_VCN_172-28_SANDBOX_2 {
  attached_views {
    view_id = oci_dns_view.export_VCN_172-28_SANDBOX_1.id
  }
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-13T15:55:50.701Z"
  }
  display_name = "VCN_172.28_SANDBOX"
  freeform_tags = {
  }
  resolver_id = "ocid1.dnsresolver.oc1.iad.amaaaaaalryh7qaabmgrertpequgicejxuvn7v7nz7iqtznbsmzfktngfihq"
  rules {
    action = "FORWARD"
    client_address_conditions = [
    ]
    destination_addresses = [
      "172.28.104.8",
    ]
    qname_cover_conditions = [
      "perseustech.corp",
    ]
    source_endpoint_name = "perseus_corp_endpoint_forwarding_01"
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver_endpoint export_perseus_corp_endpoint_forwarding_01_1 {
  endpoint_type      = "VNIC"
  forwarding_address = "172.28.104.3"
  is_forwarding      = "true"
  is_listening       = "false"
  #listening_address = <<Optional value not found in discovery>>
  name = "perseus_corp_endpoint_forwarding_01"
  nsg_ids = [
  ]
  resolver_id = "ocid1.dnsresolver.oc1.iad.amaaaaaalryh7qaabmgrertpequgicejxuvn7v7nz7iqtznbsmzfktngfihq"
  #scope = <<Optional value not found in discovery>>
  subnet_id = oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_04.id
}

resource oci_dns_resolver_endpoint export_perseus_corp_endpoint_listening_1 {
  endpoint_type = "VNIC"
  #forwarding_address = <<Optional value not found in discovery>>
  is_forwarding     = "false"
  is_listening      = "true"
  listening_address = "172.28.104.2"
  name              = "perseus_corp_endpoint_listening"
  nsg_ids = [
  ]
  resolver_id = "ocid1.dnsresolver.oc1.iad.amaaaaaalryh7qaabmgrertpequgicejxuvn7v7nz7iqtznbsmzfktngfihq"
  #scope = <<Optional value not found in discovery>>
  subnet_id = oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_04.id
}

resource oci_dns_zone export_hmlpriv04-vcn17228sandbox-oraclevcn-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-30T21:26:27.789Z"
  }
  freeform_tags = {
  }
  name      = "hmlpriv04.vcn17228sandbox.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN_172-28_SANDBOX_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-18T19:16:31.354Z"
  }
  freeform_tags = {
  }
  name      = "subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN_172-28_SANDBOX_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_redeprivada02-vcn17228sandbox-oraclevcn-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-13T15:58:04.612Z"
  }
  freeform_tags = {
  }
  name      = "redeprivada02.vcn17228sandbox.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN_172-28_SANDBOX_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_redeprivada01-vcn17228sandbox-oraclevcn-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-13T15:57:35.910Z"
  }
  freeform_tags = {
  }
  name      = "redeprivada01.vcn17228sandbox.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN_172-28_SANDBOX_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_redepublica01-vcn17228sandbox-oraclevcn-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-13T15:57:00.823Z"
  }
  freeform_tags = {
  }
  name      = "redepublica01.vcn17228sandbox.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN_172-28_SANDBOX_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_28-172-in-addr-arpa {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-13T15:55:50.701Z"
  }
  freeform_tags = {
  }
  name      = "28.172.in-addr.arpa"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN_172-28_SANDBOX_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hml--zap-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-zap.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-zap.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.41"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_perseus--corp--endpoint--listening-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "perseus-corp-endpoint-listening.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "perseus-corp-endpoint-listening.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.2"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_teste--vpn--britech-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "teste-vpn-britech.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "teste-vpn-britech.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.203"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hml--britech--01-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-britech-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-britech-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.61"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hml--sql--ter02-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-sql-ter02.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-sql-ter02.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.192"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_minhaconta--sandbox-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "minhaconta-sandbox.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "minhaconta-sandbox.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.162"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_perseus--corp--endpoint--forwarding--01-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "perseus-corp-endpoint-forwarding-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "perseus-corp-endpoint-forwarding-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.34"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hmlpriv04-vcn17228sandbox-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hmlpriv04-vcn17228sandbox-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 41 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_host--172--28--104--100-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-104-100.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-104-100.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.100"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hml--ad--02-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-ad-02.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-ad-02.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.8"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hml--cfi--01-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-cfi-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-cfi-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.103"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hml--jdsp--01-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-jdsp-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-jdsp-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.138"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hml--sql--ter01-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-sql-ter01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-sql-ter01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.171"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_hmlpriv04-vcn17228sandbox-oraclevcn-com_hml--tema--01-hmlpriv04-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-tema-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-tema-01.hmlpriv04.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.104.198"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_hmlpriv04-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com_oke--c6iqd5jscla--ng3vb2iw44a--sn3gmo2uxxq--6-subhmlprivashbu-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-6.subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-6.subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.123.202"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com_subhmlprivashbu-vcn17228sandbox-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com_subhmlprivashbu-vcn17228sandbox-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 563 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com_hml--crk--01-subhmlprivashbu-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-crk-01.subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-crk-01.subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.123.249"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com_oke--c6iqd5jscla--ng3vb2iw44a--sn3gmo2uxxq--1-subhmlprivashbu-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-1.subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-1.subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.118.45"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com_oke--c6iqd5jscla--ng3vb2iw44a--sn3gmo2uxxq--2-subhmlprivashbu-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-2.subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-2.subhmlprivashbu.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.116.246"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subhmlprivashbu-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada02-vcn17228sandbox-oraclevcn-com_oke--c6iqd5jscla--nf4bulvf7ra--sxejywop4oa--0-redeprivada02-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "oke-c6iqd5jscla-nf4bulvf7ra-sxejywop4oa-0.redeprivada02.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "oke-c6iqd5jscla-nf4bulvf7ra-sxejywop4oa-0.redeprivada02.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.102.247"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada02-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada02-vcn17228sandbox-oraclevcn-com_redeprivada02-vcn17228sandbox-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "redeprivada02.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "redeprivada02.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada02-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada02-vcn17228sandbox-oraclevcn-com_redeprivada02-vcn17228sandbox-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "redeprivada02.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "redeprivada02.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 30 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada02-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--179-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-179.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-179.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.179"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--202-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-202.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-202.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.202"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--214-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-214.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-214.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.214"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_jenkins-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "jenkins.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "jenkins.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.170"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--105-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-105.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-105.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.105"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--144-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-144.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-144.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.144"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--131-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-131.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-131.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.131"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--166-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-166.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-166.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.166"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--208-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-208.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-208.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.208"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_hml--rabbitmq--01-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-rabbitmq-01.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-rabbitmq-01.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.219"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_hml--sftp--01-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-sftp-01.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-sftp-01.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.91"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--42-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-42.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-42.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.42"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_redeprivada01-vcn17228sandbox-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_redeprivada01-vcn17228sandbox-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 61 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--148-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-148.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-148.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.148"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--206-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-206.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-206.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.206"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--55-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-55.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-55.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.55"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--88-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-88.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-88.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.88"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_runner-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "runner.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "runner.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.184"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--126-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-126.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-126.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.126"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--185-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-185.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-185.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.185"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--157-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-157.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-157.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.157"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--220-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-220.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-220.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.220"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_perseus--teste--01-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "perseus-teste-01.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "perseus-teste-01.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.207"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_hml--elastic--01-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-elastic-01.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-elastic-01.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.191"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--130-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-130.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-130.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.130"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--151-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-151.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-151.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.151"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--222-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-222.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-222.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.222"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--155-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-155.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-155.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.155"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redeprivada01-vcn17228sandbox-oraclevcn-com_host--172--28--100--209-redeprivada01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-100-209.redeprivada01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-100-209.redeprivada01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.100.209"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redeprivada01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redepublica01-vcn17228sandbox-oraclevcn-com_host--172--28--101--216-redepublica01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-101-216.redepublica01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-101-216.redepublica01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.101.216"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redepublica01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redepublica01-vcn17228sandbox-oraclevcn-com_openvpn-redepublica01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "openvpn.redepublica01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "openvpn.redepublica01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.101.248"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redepublica01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redepublica01-vcn17228sandbox-oraclevcn-com_postgres--sandbox--01-redepublica01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "postgres-sandbox-01.redepublica01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "postgres-sandbox-01.redepublica01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.101.62"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redepublica01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redepublica01-vcn17228sandbox-oraclevcn-com_redepublica01-vcn17228sandbox-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "redepublica01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "redepublica01.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redepublica01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redepublica01-vcn17228sandbox-oraclevcn-com_redepublica01-vcn17228sandbox-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "redepublica01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "redepublica01.vcn17228sandbox.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 38 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redepublica01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redepublica01-vcn17228sandbox-oraclevcn-com_c6iqd5jscla-redepublica01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "c6iqd5jscla.redepublica01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "c6iqd5jscla.redepublica01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.101.164"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redepublica01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redepublica01-vcn17228sandbox-oraclevcn-com_hml--jump--02-redepublica01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "hml-jump-02.redepublica01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "hml-jump-02.redepublica01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.101.2"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redepublica01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_redepublica01-vcn17228sandbox-oraclevcn-com_host--172--28--101--191-redepublica01-vcn17228sandbox-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-172-28-101-191.redepublica01.vcn17228sandbox.oraclevcn.com"
  items {
    domain = "host-172-28-101-191.redepublica01.vcn17228sandbox.oraclevcn.com"
    rdata  = "172.28.101.191"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_redepublica01-vcn17228sandbox-oraclevcn-com.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_144-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "144.100.28.172.in-addr.arpa"
  items {
    domain = "144.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-144.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_155-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "155.100.28.172.in-addr.arpa"
  items {
    domain = "155.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-155.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_219-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "219.100.28.172.in-addr.arpa"
  items {
    domain = "219.100.28.172.in-addr.arpa"
    rdata  = "hml-rabbitmq-01.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_222-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "222.100.28.172.in-addr.arpa"
  items {
    domain = "222.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-222.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_131-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "131.100.28.172.in-addr.arpa"
  items {
    domain = "131.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-131.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_2-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "2.104.28.172.in-addr.arpa"
  items {
    domain = "2.104.28.172.in-addr.arpa"
    rdata  = "perseus-corp-endpoint-listening.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_41-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "41.104.28.172.in-addr.arpa"
  items {
    domain = "41.104.28.172.in-addr.arpa"
    rdata  = "hml-zap.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_171-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "171.104.28.172.in-addr.arpa"
  items {
    domain = "171.104.28.172.in-addr.arpa"
    rdata  = "hml-sql-ter01.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_28-172-in--addr-arpa_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "28.172.in-addr.arpa"
  items {
    domain = "28.172.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_28-172-in--addr-arpa_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "28.172.in-addr.arpa"
  items {
    domain = "28.172.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 726 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_179-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "179.100.28.172.in-addr.arpa"
  items {
    domain = "179.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-179.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_202-123-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "202.123.28.172.in-addr.arpa"
  items {
    domain = "202.123.28.172.in-addr.arpa"
    rdata  = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-6.subhmlprivashbu.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_8-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "8.104.28.172.in-addr.arpa"
  items {
    domain = "8.104.28.172.in-addr.arpa"
    rdata  = "hml-ad-02.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_151-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "151.100.28.172.in-addr.arpa"
  items {
    domain = "151.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-151.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_198-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "198.104.28.172.in-addr.arpa"
  items {
    domain = "198.104.28.172.in-addr.arpa"
    rdata  = "hml-tema-01.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_208-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "208.100.28.172.in-addr.arpa"
  items {
    domain = "208.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-208.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_173-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "173.100.28.172.in-addr.arpa"
  items {
    domain = "173.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-173.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_220-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "220.100.28.172.in-addr.arpa"
  items {
    domain = "220.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-220.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_247-102-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "247.102.28.172.in-addr.arpa"
  items {
    domain = "247.102.28.172.in-addr.arpa"
    rdata  = "oke-c6iqd5jscla-nf4bulvf7ra-sxejywop4oa-0.redeprivada02.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_45-118-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "45.118.28.172.in-addr.arpa"
  items {
    domain = "45.118.28.172.in-addr.arpa"
    rdata  = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-1.subhmlprivashbu.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_214-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "214.100.28.172.in-addr.arpa"
  items {
    domain = "214.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-214.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_164-101-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "164.101.28.172.in-addr.arpa"
  items {
    domain = "164.101.28.172.in-addr.arpa"
    rdata  = "c6iqd5jscla.redepublica01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_185-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "185.100.28.172.in-addr.arpa"
  items {
    domain = "185.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-185.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_138-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "138.104.28.172.in-addr.arpa"
  items {
    domain = "138.104.28.172.in-addr.arpa"
    rdata  = "hml-jdsp-01.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_206-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "206.100.28.172.in-addr.arpa"
  items {
    domain = "206.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-206.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_216-101-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "216.101.28.172.in-addr.arpa"
  items {
    domain = "216.101.28.172.in-addr.arpa"
    rdata  = "host-172-28-101-216.redepublica01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_248-101-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "248.101.28.172.in-addr.arpa"
  items {
    domain = "248.101.28.172.in-addr.arpa"
    rdata  = "openvpn.redepublica01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_34-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "34.104.28.172.in-addr.arpa"
  items {
    domain = "34.104.28.172.in-addr.arpa"
    rdata  = "perseus-corp-endpoint-forwarding-01.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_184-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "184.100.28.172.in-addr.arpa"
  items {
    domain = "184.100.28.172.in-addr.arpa"
    rdata  = "runner.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_192-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "192.104.28.172.in-addr.arpa"
  items {
    domain = "192.104.28.172.in-addr.arpa"
    rdata  = "hml-sql-ter02.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_2-101-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "2.101.28.172.in-addr.arpa"
  items {
    domain = "2.101.28.172.in-addr.arpa"
    rdata  = "hml-jump-02.redepublica01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_202-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "202.100.28.172.in-addr.arpa"
  items {
    domain = "202.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-202.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_209-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "209.100.28.172.in-addr.arpa"
  items {
    domain = "209.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-209.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_170-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "170.100.28.172.in-addr.arpa"
  items {
    domain = "170.100.28.172.in-addr.arpa"
    rdata  = "jenkins.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_88-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "88.100.28.172.in-addr.arpa"
  items {
    domain = "88.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-88.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_162-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "162.104.28.172.in-addr.arpa"
  items {
    domain = "162.104.28.172.in-addr.arpa"
    rdata  = "minhaconta-sandbox.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_157-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "157.100.28.172.in-addr.arpa"
  items {
    domain = "157.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-157.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_91-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "91.100.28.172.in-addr.arpa"
  items {
    domain = "91.100.28.172.in-addr.arpa"
    rdata  = "hml-sftp-01.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_148-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "148.100.28.172.in-addr.arpa"
  items {
    domain = "148.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-148.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_103-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "103.104.28.172.in-addr.arpa"
  items {
    domain = "103.104.28.172.in-addr.arpa"
    rdata  = "hml-cfi-01.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_130-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "130.100.28.172.in-addr.arpa"
  items {
    domain = "130.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-130.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_166-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "166.100.28.172.in-addr.arpa"
  items {
    domain = "166.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-166.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_203-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "203.104.28.172.in-addr.arpa"
  items {
    domain = "203.104.28.172.in-addr.arpa"
    rdata  = "teste-vpn-britech.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_100-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "100.104.28.172.in-addr.arpa"
  items {
    domain = "100.104.28.172.in-addr.arpa"
    rdata  = "host-172-28-104-100.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_191-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "191.100.28.172.in-addr.arpa"
  items {
    domain = "191.100.28.172.in-addr.arpa"
    rdata  = "hml-elastic-01.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_246-116-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "246.116.28.172.in-addr.arpa"
  items {
    domain = "246.116.28.172.in-addr.arpa"
    rdata  = "oke-c6iqd5jscla-ng3vb2iw44a-sn3gmo2uxxq-2.subhmlprivashbu.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_249-123-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "249.123.28.172.in-addr.arpa"
  items {
    domain = "249.123.28.172.in-addr.arpa"
    rdata  = "hml-crk-01.subhmlprivashbu.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_42-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "42.100.28.172.in-addr.arpa"
  items {
    domain = "42.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-42.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_126-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "126.100.28.172.in-addr.arpa"
  items {
    domain = "126.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-126.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_55-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "55.100.28.172.in-addr.arpa"
  items {
    domain = "55.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-55.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_105-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "105.100.28.172.in-addr.arpa"
  items {
    domain = "105.100.28.172.in-addr.arpa"
    rdata  = "host-172-28-100-105.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_207-100-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "207.100.28.172.in-addr.arpa"
  items {
    domain = "207.100.28.172.in-addr.arpa"
    rdata  = "perseus-teste-01.redeprivada01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_191-101-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "191.101.28.172.in-addr.arpa"
  items {
    domain = "191.101.28.172.in-addr.arpa"
    rdata  = "host-172-28-101-191.redepublica01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_62-101-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "62.101.28.172.in-addr.arpa"
  items {
    domain = "62.101.28.172.in-addr.arpa"
    rdata  = "postgres-sandbox-01.redepublica01.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

resource oci_dns_rrset export_28-172-in-addr-arpa_61-104-28-172-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "61.104.28.172.in-addr.arpa"
  items {
    domain = "61.104.28.172.in-addr.arpa"
    rdata  = "hml-britech-01.hmlpriv04.vcn17228sandbox.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_28-172-in-addr-arpa.id
}

