## This configuration was generated by terraform-provider-oci

resource oci_file_storage_export export_export {
  export_options {
    access = "READ_WRITE"
    allowed_auth = [
      "SYS",
    ]
    anonymous_gid                  = "65534"
    anonymous_uid                  = "65534"
    identity_squash                = "NONE"
    is_anonymous_access_allowed    = "false"
    require_privileged_source_port = "false"
    source                         = "0.0.0.0/0"
  }
  export_set_id                = "ocid1.exportset.oc1.iad.aaaaacvippzulxd7nfqwillqojxwiotjmfsc2ylefuzaaaaa"
  file_system_id               = oci_file_storage_file_system.export_csi-fss-7c01a0de-bc7e-460f-a4a2-4d8ebf3b70b9.id
  is_idmap_groups_for_sys_auth = "false"
  path                         = "/nfs-efs-mc-shared-sandbox-02"
}

resource oci_file_storage_export export_export_1 {
  export_options {
    access = "READ_WRITE"
    allowed_auth = [
      "SYS",
    ]
    anonymous_gid                  = "65534"
    anonymous_uid                  = "65534"
    identity_squash                = "NONE"
    is_anonymous_access_allowed    = "false"
    require_privileged_source_port = "false"
    source                         = "0.0.0.0/0"
  }
  export_set_id                = "ocid1.exportset.oc1.iad.aaaaacvippzulxd7nfqwillqojxwiotjmfsc2ylefuzaaaaa"
  file_system_id               = oci_file_storage_file_system.export_nfs-efs-mc-shared-sandbox.id
  is_idmap_groups_for_sys_auth = "false"
  path                         = "/nfs-efs-mc-shared-sandbox"
}

