## This configuration was generated by terraform-provider-oci

resource oci_license_manager_configuration export_configuration {
  compartment_id = "ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq"
  email_ids = [
  ]
}

