## This configuration was generated by terraform-provider-oci

resource oci_ons_notification_topic export_Heron-Topic {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-11-27T20:17:05.885Z"
  }
  #description = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "Heron-Topic"
}

resource oci_ons_subscription export_subscription {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-11-27T20:17:33.885Z"
  }
  delivery_policy = "{\"backoffRetryPolicy\":{\"maxRetryDuration\":7200000,\"policyType\":\"EXPONENTIAL\"}}"
  endpoint        = "heron@perseustech.dev"
  freeform_tags = {
  }
  protocol = "EMAIL"
  topic_id = oci_ons_notification_topic.export_Heron-Topic.id
}

