## This configuration was generated by terraform-provider-oci

resource oci_vn_monitoring_path_analyzer_test export_Fnet {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2024-03-05T17:26:12.417Z"
  }
  destination_endpoint {
    address = "200.160.161.172"
    #instance_id = <<Optional value not found in discovery>>
    #listener_id = <<Optional value not found in discovery>>
    #load_balancer_id = <<Optional value not found in discovery>>
    #network_load_balancer_id = <<Optional value not found in discovery>>
    #subnet_id = <<Optional value not found in discovery>>
    type = "ON_PREM"
    #vlan_id = <<Optional value not found in discovery>>
    #vnic_id = <<Optional value not found in discovery>>
  }
  display_name = "Fnet"
  freeform_tags = {
  }
  protocol = "6"
  protocol_parameters {
    destination_port = "443"
    #icmp_code = <<Optional value not found in discovery>>
    #icmp_type = <<Optional value not found in discovery>>
    #source_port = <<Optional value not found in discovery>>
    type = "TCP"
  }
  query_options {
    is_bi_directional_analysis = "true"
  }
  source_endpoint {
    address = "172.28.101.2"
    #instance_id = <<Optional value not found in discovery>>
    #listener_id = <<Optional value not found in discovery>>
    #load_balancer_id = <<Optional value not found in discovery>>
    #network_load_balancer_id = <<Optional value not found in discovery>>
    #subnet_id = <<Optional value not found in discovery>>
    type = "IP_ADDRESS"
    #vlan_id = <<Optional value not found in discovery>>
    #vnic_id = <<Optional value not found in discovery>>
  }
}

