## This configuration was generated by terraform-provider-oci

resource oci_waf_web_app_firewall_policy export_sandbox-access-mp {
  actions {
    #body = <<Optional value not found in discovery>>
    #code = <<Optional value not found in discovery>>
    #headers = <<Optional value not found in discovery>>
    name = "Pre-configured Check Action"
    type = "CHECK"
  }
  actions {
    #body = <<Optional value not found in discovery>>
    #code = <<Optional value not found in discovery>>
    #headers = <<Optional value not found in discovery>>
    name = "Pre-configured Allow Action"
    type = "ALLOW"
  }
  actions {
    body {
      text = "{\"code\":\"401\",\"message\":\"Unauthorized\"}"
      type = "STATIC_TEXT"
    }
    code = "401"
    headers {
      name  = "Content-Type"
      value = "application/json"
    }
    name = "Pre-configured 401 Response Code Action"
    type = "RETURN_HTTP_RESPONSE"
  }
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T17:50:27.830Z"
  }
  display_name = "sandbox-access-mp"
  freeform_tags = {
  }
  request_access_control {
    default_action_name = "Pre-configured Allow Action"
    rules {
      action_name        = "Pre-configured 401 Response Code Action"
      condition          = "!address_in(connection.source.address, ['150.136.31.72/32','54.88.218.97/32','18.215.140.160/32','18.213.114.129/32','18.206.34.84/32','35.236.253.169/32','35.245.91.34/32','35.245.20.104/32','35.186.182.146/32','8.243.39.190/32','179.127.197.76/32','18.206.34.84/32','190.210.134.125/32','54.88.218.97/32','18.213.114.129/32','18.215.140.160/32','64.191.220.148/32'])"
      condition_language = "JMESPATH"
      name               = "MP-IPs"
      type               = "ACCESS_CONTROL"
    }
  }
  request_protection {
    #body_inspection_size_limit_exceeded_action_name = <<Optional value not found in discovery>>
    body_inspection_size_limit_in_bytes = "8192"
  }
  response_access_control {
  }
  system_tags = {
    "orcl-cloud.free-tier-retained" = "false"
  }
}

resource oci_waf_web_app_firewall export_webappfirewall20231219175057 {
  backend_type   = "LOAD_BALANCER"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T17:50:57.733Z"
  }
  display_name = "webappfirewall20231219175057"
  freeform_tags = {
  }
  load_balancer_id = oci_load_balancer_load_balancer.export_sandbox-mp-mc.id
  system_tags = {
    "orcl-cloud.free-tier-retained" = "false"
  }
  web_app_firewall_policy_id = oci_waf_web_app_firewall_policy.export_sandbox-access-mp.id
}

