## This configuration was generated by terraform-provider-oci

resource oci_cloud_bridge_inventory export_Inventory_20231221141025 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-21T14:10:30.738Z"
  }
  display_name = "Inventory_20231221141025"
  freeform_tags = {
  }
}

