## This configuration was generated by terraform-provider-oci

resource oci_devops_build_pipeline export_PipelineDeploy {
  build_pipeline_parameters {
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-11-27T20:18:16.911Z"
  }
  description  = ""
  display_name = "PipelineDeploy"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_DevOps_Project.id
}

resource oci_devops_deploy_environment export_Staging {
  cluster_id = oci_containerengine_cluster.export_hml-oke-02.id
  #compute_instance_group_selectors = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-11-27T20:19:42.515Z"
  }
  deploy_environment_type = "OKE_CLUSTER"
  description             = ""
  display_name            = "Staging"
  freeform_tags = {
  }
  #function_id = <<Optional value not found in discovery>>
  project_id = oci_devops_project.export_DevOps_Project.id
}

resource oci_devops_project export_DevOps_Project {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-11-27T20:17:46.716Z"
  }
  description = ""
  freeform_tags = {
  }
  name = "DevOps_Project"
  notification_config {
    topic_id = oci_ons_notification_topic.export_Heron-Topic.id
  }
}

resource oci_devops_project_repository_setting export_DevOps_Project_project_repository_setting {
  approval_rules {
  }
  merge_settings {
    allowed_merge_strategies = [
      "MERGE_COMMIT",
    ]
    default_merge_strategy = "MERGE_COMMIT"
  }
  project_id = oci_devops_project.export_DevOps_Project.id
}

