## This configuration was generated by terraform-provider-oci

resource oci_identity_compartment export_PerseusTech-SA {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T15:44:21.895Z"
  }
  description = "perseustech-root"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "PerseusTech-SA"
}

resource oci_identity_policy export_hml-oke-02-access {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-04-08T15:42:33.456Z"
  }
  description = "permitir o grupo hml-oke-02-access acessar o cluster"
  freeform_tags = {
  }
  name = "hml-oke-02-access"
  statements = [
    "Allow group 'Default'/'Hml-OKE-02-Access' to use clusters in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_k8s_csi_volume {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-23T01:09:09.660Z"
  }
  description = "k8s_csi_volume"
  freeform_tags = {
  }
  name = "k8s_csi_volume"
  statements = [
    "ALLOW any-user to manage file-family in TENANCY where request.principal.type = 'cluster'",
    "ALLOW any-user to use virtual-network-family in TENANCY where request.principal.type = 'cluster'",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_oke-cluster-autoscaler-dyn-grp-policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-04-10T14:39:30.388Z"
  }
  description = "oke-cluster-autoscaler-dyn-grp-policy"
  freeform_tags = {
  }
  name = "oke-cluster-autoscaler-dyn-grp-policy"
  statements = [
    "Allow dynamic-group oke-cluster-autoscaler-dyn-grp to manage cluster-node-pools in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
    "Allow dynamic-group oke-cluster-autoscaler-dyn-grp to manage instance-family in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
    "Allow dynamic-group oke-cluster-autoscaler-dyn-grp to use subnets in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
    "Allow dynamic-group oke-cluster-autoscaler-dyn-grp to read virtual-network-family in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
    "Allow dynamic-group oke-cluster-autoscaler-dyn-grp to use vnics in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
    "Allow dynamic-group oke-cluster-autoscaler-dyn-grp to inspect compartments in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_OKE-Virtual-Nodes {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-04-09T17:20:31.504Z"
  }
  description = "Container Engine for Kubernetes service to allow virtual nodes to create container instances in the Container Engine for Kubernetes service tenancy"
  freeform_tags = {
  }
  name = "OKE-Virtual-Nodes"
  statements = [
    "define tenancy ske as ocid1.tenancy.oc1..aaaaaaaacrvwsphodcje6wfbc3xsixhzcan5zihki6bvc7xkwqds4tqhzbaq",
    "define compartment ske_compartment as ocid1.compartment.oc1..aaaaaaaa2bou6r766wmrh5zt3vhu2rwdya7ahn4dfdtwzowb662cmtdc5fea",
    "endorse any-user to associate compute-container-instances in compartment ske_compartment of tenancy ske with subnets in tenancy where ALL {request.principal.type='virtualnode',request.operation='CreateContainerInstance',request.principal.subnet=2.subnet.id}",
    "endorse any-user to associate compute-container-instances in compartment ske_compartment of tenancy ske with vnics in tenancy where ALL {request.principal.type='virtualnode',request.operation='CreateContainerInstance',request.principal.subnet=2.subnet.id}",
    "endorse any-user to associate compute-container-instances in compartment ske_compartment of tenancy ske with network-security-group in tenancy where ALL {request.principal.type='virtualnode',request.operation='CreateContainerInstance'}",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_prd-oke-01-cluster-autoscaler-dyn-grp-policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-27T13:36:29.546Z"
  }
  description = "prd-oke-01-cluster-autoscaler-dyn-grp-policy"
  freeform_tags = {
  }
  name = "prd-oke-01-cluster-autoscaler-dyn-grp-policy"
  statements = [
    "Allow dynamic-group prd-oke-01-cluster-autoscaler-dyn-grp to manage cluster-node-pools in compartment  id ocid1.compartment.oc1..aaaaaaaa4prz2lmhkujiwp35gsrbrqbvkpro6jooopwajr75ytmg6rbn3pvq",
    "Allow dynamic-group prd-oke-01-cluster-autoscaler-dyn-grp to manage instance-family in compartment id  ocid1.compartment.oc1..aaaaaaaa4prz2lmhkujiwp35gsrbrqbvkpro6jooopwajr75ytmg6rbn3pvq",
    "Allow dynamic-group prd-oke-01-cluster-autoscaler-dyn-grp to use subnets in compartment id ocid1.compartment.oc1..aaaaaaaa4prz2lmhkujiwp35gsrbrqbvkpro6jooopwajr75ytmg6rbn3pvq",
    "Allow dynamic-group prd-oke-01-cluster-autoscaler-dyn-grp to read virtual-network-family in compartment id ocid1.compartment.oc1..aaaaaaaa4prz2lmhkujiwp35gsrbrqbvkpro6jooopwajr75ytmg6rbn3pvq",
    "Allow dynamic-group prd-oke-01-cluster-autoscaler-dyn-grp to use vnics in compartment id ocid1.compartment.oc1..aaaaaaaa4prz2lmhkujiwp35gsrbrqbvkpro6jooopwajr75ytmg6rbn3pvq",
    "Allow dynamic-group prd-oke-01-cluster-autoscaler-dyn-grp to inspect compartments in compartment id  ocid1.compartment.oc1..aaaaaaaa4prz2lmhkujiwp35gsrbrqbvkpro6jooopwajr75ytmg6rbn3pvq",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_Readonly {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-05T14:00:28.459Z"
  }
  description = "Readonly"
  freeform_tags = {
  }
  name = "Readonly"
  statements = [
    "Allow group Readonly to read all-resources in tenancy",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_Tenant-Admin-Policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "Tenant Admin Policy"
  freeform_tags = {
  }
  name = "Tenant Admin Policy"
  statements = [
    "ALLOW GROUP Administrators to manage all-resources IN TENANCY",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_user-virtual-nodes {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-04-09T17:26:18.413Z"
  }
  description = "create and use clusters with virtual nodes and virtual node pools"
  freeform_tags = {
  }
  name = "user-virtual-nodes"
  statements = [
    "allow group Hml-OKE-02-Access to manage cluster-virtualnode-pools in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
    "allow group Hml-OKE-02-Access to read virtual-network-family in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
    "allow group Hml-OKE-02-Access to manage vnics in compartment id ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_VNPA-Tenancy-Policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2023-11-24T14:14:54.034Z"
  }
  description = "VNPA-Exec-Policy description"
  freeform_tags = {
  }
  name = "VNPA-Tenancy-Policy"
  statements = [
    "allow any-user to inspect compartments in tenancy where all { request.principal.type = 'vnpa-service' }",
    "allow any-user to read instances in tenancy where all { request.principal.type = 'vnpa-service' }",
    "allow any-user to read virtual-network-family in tenancy where all { request.principal.type = 'vnpa-service' }",
    "allow any-user to read load-balancers in tenancy where all { request.principal.type = 'vnpa-service' }",
    "allow any-user to read network-security-group in tenancy where all { request.principal.type = 'vnpa-service' }",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_domain export_Default {
  #admin_email = <<Optional value not found in discovery>>
  #admin_first_name = <<Optional value not found in discovery>>
  #admin_last_name = <<Optional value not found in discovery>>
  #admin_user_name = <<Optional value not found in discovery>>
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description  = "Default domain"
  display_name = "Default"
  freeform_tags = {
  }
  home_region        = "us-ashburn-1"
  is_hidden_on_login = "false"
  #is_notification_bypassed = <<Optional value not found in discovery>>
  #is_primary_email_required = <<Optional value not found in discovery>>
  license_type = "free"
  state        = "ACTIVE"
}

resource oci_identity_dynamic_group export_oke-cluster-autoscaler-dyn-grp {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-04-10T14:36:41.319Z"
  }
  description = "oke-cluster-autoscaler-dyn-grp"
  freeform_tags = {
  }
  matching_rule = "Any {ALL {instance.compartment.id = 'ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq'}}"
  name          = "oke-cluster-autoscaler-dyn-grp"
}

resource oci_identity_dynamic_group export_prd-oke-01-cluster-autoscaler-dyn-grp {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-27T13:17:47.507Z"
  }
  description = "prd-oke-01-cluster-autoscaler-dyn-grp"
  freeform_tags = {
  }
  matching_rule = "Any {ALL {instance.compartment.id = 'ocid1.compartment.oc1..aaaaaaaa4prz2lmhkujiwp35gsrbrqbvkpro6jooopwajr75ytmg6rbn3pvq'}}"
  name          = "prd-oke-01-cluster-autoscaler-dyn-grp"
}

resource oci_identity_authentication_policy export_authentication_policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  network_policy {
    network_source_ids = [
    ]
  }
  password_policy {
    is_lowercase_characters_required = "true"
    is_numeric_characters_required   = "true"
    is_special_characters_required   = "false"
    is_uppercase_characters_required = "true"
    is_username_containment_allowed  = "false"
    minimum_password_length          = "12"
  }
}

resource oci_identity_compartment export_management {
  compartment_id = oci_identity_compartment.export_PerseusTech-SA.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T15:48:50.869Z"
  }
  description = "management"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "management"
}

resource oci_identity_compartment export_production-cliente-b {
  compartment_id = oci_identity_compartment.export_PerseusTech-SA.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-01-18T14:44:21.403Z"
  }
  description = "production-cliente-b"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "production-cliente-b"
}

resource oci_identity_compartment export_production-mp {
  compartment_id = oci_identity_compartment.export_PerseusTech-SA.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T15:51:23.514Z"
  }
  description = "production-mp"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "production-mp"
}

resource oci_identity_compartment export_rtm-fnet {
  compartment_id = oci_identity_compartment.export_PerseusTech-SA.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2024-02-14T20:16:13.639Z"
  }
  description = "Conexão Financial Net com a RTM"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "rtm-fnet"
}

resource oci_identity_compartment export_sandbox-cliente-b {
  compartment_id = oci_identity_compartment.export_PerseusTech-SA.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-01-18T14:43:47.898Z"
  }
  description = "sandbox-cliente-b"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "sandbox-cliente-b"
}

resource oci_identity_compartment export_sandbox-mp {
  compartment_id = oci_identity_compartment.export_PerseusTech-SA.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T15:46:53.344Z"
  }
  description = "sandbox"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "sandbox-mp"
}

resource oci_identity_group export_Readonly_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-05T13:58:57.459Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  freeform_tags = {
  }
  name = "Readonly"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_group export_Administrators {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "Administrators"
  freeform_tags = {
  }
  name = "Administrators"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_group export_All-Domain-Users {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "A group representing all users."
  freeform_tags = {
  }
  name = "All Domain Users"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_group export_Grafana {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/douglas.ribeiro@nikos.com.br"
    "Oracle-Tags.CreatedOn" = "2024-08-12T22:10:55.560Z"
  }
  description = "Grafana Metrics"
  freeform_tags = {
  }
  name = "Grafana"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_group export_Hml-OKE-02-Access {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-04-08T15:24:20.637Z"
  }
  description = "Grupo para acessar o cluster hml-oke-02"
  freeform_tags = {
  }
  name = "Hml-OKE-02-Access"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_caio-c-silva-oracle-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-27T12:35:55.793Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "caio.c.silva@oracle.com"
  freeform_tags = {
  }
  name = "caio.c.silva@oracle.com"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_yossef-hamdan-perseustech-dev {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-30T17:37:20.091Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "yossef.hamdan@perseustech.dev"
  freeform_tags = {
  }
  name = "yossef.hamdan@perseustech.dev"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_marcelo-quintas-perseustech-dev {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-18T15:07:19.793Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "marcelo.quintas@perseustech.dev"
  freeform_tags = {
  }
  name = "marcelo.quintas@perseustech.dev"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_anthony-baldavia-dbacorp-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-05T13:58:31.282Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "anthony.baldavia@dbacorp.com.br"
  freeform_tags = {
  }
  name = "anthony.baldavia@dbacorp.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_gabriel-antonio-orama-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-30T18:00:39.575Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "gabriel.antonio@orama.com.br"
  freeform_tags = {
  }
  name = "gabriel.antonio@orama.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_suporte-perseustech-dev {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "suporte@perseustech.dev"
  freeform_tags = {
  }
  name = "suporte@perseustech.dev"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_luiz-paiva-orama-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-11-23T17:57:28.843Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "luiz.paiva@orama.com.br"
  freeform_tags = {
  }
  name = "luiz.paiva@orama.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_cliff-bernaldo-perseustech-dev {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-31T14:12:45.800Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "cliff.bernaldo@perseustech.dev"
  freeform_tags = {
  }
  name = "cliff.bernaldo@perseustech.dev"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_thiago-filhote-nikos-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-05-22T13:23:40.403Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "thiago.filhote@nikos.com.br"
  freeform_tags = {
  }
  name = "thiago.filhote@nikos.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_andre-pontes-nikos-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/douglas.ribeiro@nikos.com.br"
    "Oracle-Tags.CreatedOn" = "2024-04-24T19:28:01.344Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "andre.pontes@nikos.com.br"
  freeform_tags = {
  }
  name = "andre.pontes@nikos.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_padmaja-vepachedu-oracle-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-27T12:37:56.305Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "padmaja.vepachedu@oracle.com"
  freeform_tags = {
  }
  name = "padmaja.vepachedu@oracle.com"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_raphael-nogueira-nikos-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-04-08T13:46:44.139Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "raphael.nogueira@nikos.com.br"
  freeform_tags = {
  }
  name = "raphael.nogueira@nikos.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_heron-brito-nikos-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-07-16T17:34:08.768Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "heron.brito@nikos.com.br"
  freeform_tags = {
  }
  name = "heron.brito@nikos.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_celso-b-junior-oracle-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-27T12:36:34.488Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "celso.b.junior@oracle.com"
  freeform_tags = {
  }
  name = "celso.b.junior@oracle.com"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_anderson-cardoso-nikos-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/douglas.ribeiro@nikos.com.br"
    "Oracle-Tags.CreatedOn" = "2024-05-07T17:20:56.207Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "anderson.cardoso@nikos.com.br"
  freeform_tags = {
  }
  name = "anderson.cardoso@nikos.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_assis-prestes-oracle-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-27T12:38:16.909Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "assis.prestes@oracle.com"
  freeform_tags = {
  }
  name = "assis.prestes@oracle.com"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_eduardo-balthar-nikos-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-03-21T15:13:44.162Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "eduardo.balthar@nikos.com.br"
  freeform_tags = {
  }
  name = "eduardo.balthar@nikos.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_dayane-gregorio-oracle-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-27T12:36:53.482Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "dayane.gregorio@oracle.com"
  freeform_tags = {
  }
  name = "dayane.gregorio@oracle.com"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_geetha-pathapati-oracle-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-06-27T12:37:22.976Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "geetha.pathapati@oracle.com"
  freeform_tags = {
  }
  name = "geetha.pathapati@oracle.com"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_douglas-ribeiro-nikos-com-br {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2024-03-14T20:38:24.439Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "douglas.ribeiro@nikos.com.br"
  freeform_tags = {
  }
  name = "douglas.ribeiro@nikos.com.br"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_ui_password export_caio-c-silva-oracle-com_ui_password {
  user_id = oci_identity_user.export_caio-c-silva-oracle-com.id
}

resource oci_identity_user_group_membership export_caio-c-silva-oracle-com_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_caio-c-silva-oracle-com.id
}

resource oci_identity_ui_password export_yossef-hamdan-perseustech-dev_ui_password {
  user_id = oci_identity_user.export_yossef-hamdan-perseustech-dev.id
}

resource oci_identity_user_group_membership export_yossef-hamdan-perseustech-dev_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_yossef-hamdan-perseustech-dev.id
}

resource oci_identity_api_key export_marcelo-quintas-perseustech-dev_api_key {
  key_value = "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnSDkk8n2W51HlChjSVqm\r\nSh9HuzPCfsFAejbP+rJOAn7lUHTiwjrETfOEcvMEQqOjF884HXaB+fPgiX7g3ImN\r\nr9+A82RkR2vvyM/LPew+z0Gcy+1DX1vpGZpXlP3Bv2ZP8UHI+Oj2OrKPCdVLmR8T\r\n2Y8t6qpSquiQyTrx+x3mD5QLlGJQryO4LvRKiK9uHDIR9fT8IFDu44lk5YJpeDch\r\n8xF9ArUjnLgzBFwMXgQag0ixb65zGgJrRDIjuzj33fBY/LoO0AksqaKwM6uSN4Ry\r\nD22xRh7tctC+kLIDM0scVcN9EVpMruOr7aC7A6pax0YuQsOlKBBeICTu2x2a72xK\r\nnQIDAQAB\r\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_marcelo-quintas-perseustech-dev.id
}

resource oci_identity_api_key export_marcelo-quintas-perseustech-dev_api_key_1 {
  key_value = "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzF/VUtNX5WrFllL1ceBH\r\nG8Cy2lfw2iJQ9RWd4jB0PUfrTS+xXjJpgQXcPcCr+CY3wQwNNVvpUiQas6XfuPZ3\r\n4YnfBWFcym/fFFLvb93quQNm24Gkkn0Iud5veHkCVwQIiPLbYknsHz79CpxPtXDv\r\nQw+R0xY+e26b+ohJWTGCJjICJ0FhM9cVp1fkCmcNC+COZRTL6aLmvZJu4HCKf/ea\r\nY99RxywBrAb7H2q8IwKRd/qqZYXbEgf6U77ERqbp3T8I78pw2MSByQaKEX69Dw6X\r\nLIA5gl410K1s4zH5ayGi0Lvv6nhhXNtlKkhAocRGWiTS/krfzjQJo6JpG0AhQo3u\r\nGwIDAQAB\r\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_marcelo-quintas-perseustech-dev.id
}

resource oci_identity_customer_secret_key export_aws-secret-rclone_1 {
  display_name = "aws-secret-rclone"
  user_id      = oci_identity_user.export_marcelo-quintas-perseustech-dev.id
}

resource oci_identity_ui_password export_marcelo-quintas-perseustech-dev_ui_password {
  user_id = oci_identity_user.export_marcelo-quintas-perseustech-dev.id
}

resource oci_identity_user_group_membership export_marcelo-quintas-perseustech-dev_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_marcelo-quintas-perseustech-dev.id
}

resource oci_identity_user_group_membership export_marcelo-quintas-perseustech-dev_user_group_membership_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Hml-OKE-02-Access.id
  user_id        = oci_identity_user.export_marcelo-quintas-perseustech-dev.id
}

resource oci_identity_ui_password export_anthony-baldavia-dbacorp-com-br_ui_password {
  user_id = oci_identity_user.export_anthony-baldavia-dbacorp-com-br.id
}

resource oci_identity_user_group_membership export_anthony-baldavia-dbacorp-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Readonly_1.id
  user_id        = oci_identity_user.export_anthony-baldavia-dbacorp-com-br.id
}

resource oci_identity_ui_password export_gabriel-antonio-orama-com-br_ui_password {
  user_id = oci_identity_user.export_gabriel-antonio-orama-com-br.id
}

resource oci_identity_user_group_membership export_gabriel-antonio-orama-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_gabriel-antonio-orama-com-br.id
}

resource oci_identity_api_key export_suporte-perseustech-dev_api_key {
  key_value = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj2frK+DA2P01gAgPxobe\nwNSmiqKrg44WGmRQ6H/T/rxepWGCRS2gHqPQyLrMzZymMBtpbJ3+1BO2L7cmop1h\nGf8SlTvSe/KXl0rJpGaciV/bOmwJm4mfk2n4RpxrhFsMDBEVzg/ioM0SxgtxpnIX\n9JIigdQCa6L4hjXWxljJoBMreutaAuUHYQssK13WyBqdBJpDtNR41m0qTGEU+9Av\nn//Pkbz425yWltrAbiIL6MPTx3Ym5W6hMfdX55it9WPIRzKkZ0eVL622f7C1/E+v\n0/RxCaVlJACG5lpgX/UejlWK9KwIPf7G5rDBo7vwJKsI80eYC6jPop3DUz83GrgF\nAwIDAQAB\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_suporte-perseustech-dev.id
}

resource oci_identity_ui_password export_suporte-perseustech-dev_ui_password {
  user_id = oci_identity_user.export_suporte-perseustech-dev.id
}

resource oci_identity_user_group_membership export_suporte-perseustech-dev_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_suporte-perseustech-dev.id
}

resource oci_identity_user_group_membership export_suporte-perseustech-dev_user_group_membership_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Hml-OKE-02-Access.id
  user_id        = oci_identity_user.export_suporte-perseustech-dev.id
}

resource oci_identity_api_key export_luiz-paiva-orama-com-br_api_key {
  key_value = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA14Jb3Gd4inb4KkDrHYb3\nxthHZn3mwHGUneFYg6rD11NvJBVhZPZq2VONK9VQC3Y7jtMeFnafhjxlPrWHyMbh\n/gKVHQ+I1i7f5rl7a5iQfaJF1aBPEXix7a0Ezhy1cyTk6kA9ucEQ/ttgJwG597nH\nT+eEoMWBWiY9yyQahdC7pjp+zSpMEvS1Or1gAU6ACCCdLe8InO3cg+AafZD2Yf6w\nbnBGPUbtsNwgQdOFtVNUBgCUb6yuV41PP32Dz9Otf4dKetHDLGMBHyfqoaFUdWek\nR24rHG0gdhqvmFOkd0CQ32a8y8HHtsqROxYj43RLcBJh2ED1O9RcDUnAtyRgBZez\nHwIDAQAB\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_luiz-paiva-orama-com-br.id
}

resource oci_identity_ui_password export_luiz-paiva-orama-com-br_ui_password {
  user_id = oci_identity_user.export_luiz-paiva-orama-com-br.id
}

resource oci_identity_user_group_membership export_luiz-paiva-orama-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_luiz-paiva-orama-com-br.id
}

resource oci_identity_api_key export_cliff-bernaldo-perseustech-dev_api_key {
  key_value = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg9vJKr5nrXv/x1oCsCMx\n9XLL+7uYC64CMYRAMUz8MxhgRnAXDDjCTLOOk3ZVtbqpMTTZBSYVFgRB5R5I1DBI\n7R9aDTGqFTTvHGlauqx02+ua6twwXHHHKcy6cFWL2rXU6G52FHIc8hxrShGKqv4Z\nY/4vfB3/H9sX8w/4sNcQ+hsYInEonLQHrqsuL8I//ffHDPvVTmQjh/GxHLcFIjbF\nQVAnoTdl75GrEbd/eNxUwS3GR582x75PxgPPa/8/N/UT8fhqhDWWZjBZhXYwb74a\n9vv3sdoK0SliORa9LM1JxtqK/a+hrsI5XI/Z40iWIMQuMSjJl0e4r4MFgJlxXrdQ\newIDAQAB\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_cliff-bernaldo-perseustech-dev.id
}

resource oci_identity_ui_password export_cliff-bernaldo-perseustech-dev_ui_password {
  user_id = oci_identity_user.export_cliff-bernaldo-perseustech-dev.id
}

resource oci_identity_user_group_membership export_cliff-bernaldo-perseustech-dev_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_cliff-bernaldo-perseustech-dev.id
}

resource oci_identity_ui_password export_thiago-filhote-nikos-com-br_ui_password {
  user_id = oci_identity_user.export_thiago-filhote-nikos-com-br.id
}

resource oci_identity_user_group_membership export_thiago-filhote-nikos-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_thiago-filhote-nikos-com-br.id
}

resource oci_identity_ui_password export_andre-pontes-nikos-com-br_ui_password {
  user_id = oci_identity_user.export_andre-pontes-nikos-com-br.id
}

resource oci_identity_user_group_membership export_andre-pontes-nikos-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_andre-pontes-nikos-com-br.id
}

resource oci_identity_ui_password export_padmaja-vepachedu-oracle-com_ui_password {
  user_id = oci_identity_user.export_padmaja-vepachedu-oracle-com.id
}

resource oci_identity_user_group_membership export_padmaja-vepachedu-oracle-com_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_padmaja-vepachedu-oracle-com.id
}

resource oci_identity_api_key export_raphael-nogueira-nikos-com-br_api_key {
  key_value = "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyCbaOipEyylBLvjtXgv1\r\nc0y36kyDU4dygzYOmDVPOZsQt5WLI0C31alSNrK+NjAfd8eR/jcYGhomoqq/8WIf\r\n3JW0mFSK41835Fy7DM/6iwhidG5VvQyM/SJjHRpwDnXxRTQw+NRjyiauOn7xvG6o\r\nhfyCbpWZH/2vnampjw+enAHcqfhMnZfcufHYUoJAUyUZFMFq+FX4IkHFKlxVZ0t7\r\nWyuEGGQl/UREYae3nGAbToEQvGY0Xzup8hTsZT+pGEm8xbt0WKNvUUq+kfik6yQT\r\nuyWwoBRP7LeoDstjhHQEwJ836JTcozwgFd0zhFMT2W6+LT6iK1vrK0/lYLYxNBcA\r\nSwIDAQAB\r\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_raphael-nogueira-nikos-com-br.id
}

resource oci_identity_ui_password export_raphael-nogueira-nikos-com-br_ui_password {
  user_id = oci_identity_user.export_raphael-nogueira-nikos-com-br.id
}

resource oci_identity_user_group_membership export_raphael-nogueira-nikos-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Hml-OKE-02-Access.id
  user_id        = oci_identity_user.export_raphael-nogueira-nikos-com-br.id
}

resource oci_identity_ui_password export_heron-brito-nikos-com-br_ui_password {
  user_id = oci_identity_user.export_heron-brito-nikos-com-br.id
}

resource oci_identity_user_group_membership export_heron-brito-nikos-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_heron-brito-nikos-com-br.id
}

resource oci_identity_ui_password export_celso-b-junior-oracle-com_ui_password {
  user_id = oci_identity_user.export_celso-b-junior-oracle-com.id
}

resource oci_identity_user_group_membership export_celso-b-junior-oracle-com_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_celso-b-junior-oracle-com.id
}

resource oci_identity_ui_password export_anderson-cardoso-nikos-com-br_ui_password {
  user_id = oci_identity_user.export_anderson-cardoso-nikos-com-br.id
}

resource oci_identity_user_group_membership export_anderson-cardoso-nikos-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_anderson-cardoso-nikos-com-br.id
}

resource oci_identity_api_key export_assis-prestes-oracle-com_api_key {
  key_value = "-----BEGIN PUBLIC KEY-----\nMIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEA+mu4VNPi+Zo1q0cxFl5d\nFljGu+1yUjHF6YmcPB0P0bt9mR4cs9swrrBOx5BZZT8KspuJn9P3WBAHRHJ1swrm\n3tQQ6DfbigUeVhhp5kuc8JOdwIWTLEljuph6sakozvqgnN3htrmRG0c148wCrpmw\nRBmOgXaHrVaE669NuCQ/e5Yj6yUGgGBwYvRpl+dRvkAX7ZIfU9008TPiaOuthyHw\nUbTEt570IrGjI/i+c3wO2I8MioTs1PhCiZ0/VLu8jUpH9miSd6HeY7tf4tIV2QTN\n6rXF4VL7B2XPymsQHNME/PE2e21mMSfE1Vf1cUdbqkgNHEP8BIVs2TwEtd1s3wsT\nRQIBJQ==\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_assis-prestes-oracle-com.id
}

resource oci_identity_ui_password export_assis-prestes-oracle-com_ui_password {
  user_id = oci_identity_user.export_assis-prestes-oracle-com.id
}

resource oci_identity_user_group_membership export_assis-prestes-oracle-com_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_assis-prestes-oracle-com.id
}

resource oci_identity_api_key export_eduardo-balthar-nikos-com-br_api_key {
  key_value = "-----BEGIN PUBLIC KEY-----\nMIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEA+mu4VNPi+Zo1q0cxFl5d\nFljGu+1yUjHF6YmcPB0P0bt9mR4cs9swrrBOx5BZZT8KspuJn9P3WBAHRHJ1swrm\n3tQQ6DfbigUeVhhp5kuc8JOdwIWTLEljuph6sakozvqgnN3htrmRG0c148wCrpmw\nRBmOgXaHrVaE669NuCQ/e5Yj6yUGgGBwYvRpl+dRvkAX7ZIfU9008TPiaOuthyHw\nUbTEt570IrGjI/i+c3wO2I8MioTs1PhCiZ0/VLu8jUpH9miSd6HeY7tf4tIV2QTN\n6rXF4VL7B2XPymsQHNME/PE2e21mMSfE1Vf1cUdbqkgNHEP8BIVs2TwEtd1s3wsT\nRQIBJQ==\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_eduardo-balthar-nikos-com-br.id
}

resource oci_identity_ui_password export_eduardo-balthar-nikos-com-br_ui_password {
  user_id = oci_identity_user.export_eduardo-balthar-nikos-com-br.id
}

resource oci_identity_user_group_membership export_eduardo-balthar-nikos-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_eduardo-balthar-nikos-com-br.id
}

resource oci_identity_ui_password export_dayane-gregorio-oracle-com_ui_password {
  user_id = oci_identity_user.export_dayane-gregorio-oracle-com.id
}

resource oci_identity_ui_password export_geetha-pathapati-oracle-com_ui_password {
  user_id = oci_identity_user.export_geetha-pathapati-oracle-com.id
}

resource oci_identity_user_group_membership export_geetha-pathapati-oracle-com_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_geetha-pathapati-oracle-com.id
}

resource oci_identity_api_key export_douglas-ribeiro-nikos-com-br_api_key {
  key_value = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl86h5B7+ubQncdqX5XAQ\nyxofM75PpTu8fMdOhJp3GXy4+3SELwgsyWQH/YZ720WYRw2a+gvGk+OuiaAKmNw5\n9/NjdkpInjbk0WZR3DacJje2a5P8/kRjLMu9ir4/wVPGW4EZi3mvqUNvl/UYZ8H0\n9cnTDOSaeXbg66pd/Na0LRlGb7EcQqeR976tRKOJe97zdD1ji+glROWCGSvTrs/4\nlkKFUbMmGL8lRLrc4kzdIdrtMlI9lKOxxNWqStEvDzW0kn8tCqDFxwPDf7JG55hE\nUTHj4fIEpmKxOHVfn4a1pDEqgT3dpXEvds2xthFsPH7HQ8Xs+AUpglt71KgNCm+P\nVQIDAQAB\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_douglas-ribeiro-nikos-com-br.id
}

resource oci_identity_ui_password export_douglas-ribeiro-nikos-com-br_ui_password {
  user_id = oci_identity_user.export_douglas-ribeiro-nikos-com-br.id
}

resource oci_identity_user_group_membership export_douglas-ribeiro-nikos-com-br_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_douglas-ribeiro-nikos-com-br.id
}

resource oci_identity_user_group_membership export_douglas-ribeiro-nikos-com-br_user_group_membership_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Hml-OKE-02-Access.id
  user_id        = oci_identity_user.export_douglas-ribeiro-nikos-com-br.id
}

