## This configuration was generated by terraform-provider-oci

resource oci_logging_log_group export_Fnet_SP {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2024-03-07T14:46:05.326Z"
  }
  description  = "Teste conexao Fnet SP"
  display_name = "Fnet_SP"
  freeform_tags = {
  }
}

resource oci_logging_log_group export_sandbox-mp-mc_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T17:19:09.287Z"
  }
  #description = <<Optional value not found in discovery>>
  display_name = "sandbox-mp-mc"
  freeform_tags = {
  }
}

resource oci_logging_log_group export_britech-teste {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2023-11-23T19:32:58.284Z"
  }
  #description = <<Optional value not found in discovery>>
  display_name = "britech-teste"
  freeform_tags = {
  }
}

resource oci_logging_log_saved_search export_Britech-web-server {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2023-11-24T14:03:31.140Z"
  }
  #description = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name  = "Britech-web-server"
  query = "search \"ocid1.tenancy.oc1..aaaaaaaa5ip333y4eunkjtck3cftl6k7fcgbsog6bdrmlynnhlcaoyofivjq/ocid1.loggroup.oc1.iad.amaaaaaalryh7qaa3qy5u5cp2icjzqngkiyspme4g6kycs7gme52s5fgxgaq/ocid1.log.oc1.iad.amaaaaaalryh7qaaobhnd6twzftlvoi2yv3j2yd52knm2xbtgztzdiydnwva\" | sort by datetime desc"
}

resource oci_logging_log export_Teste-Fnet_1 {
  configuration {
    compartment_id = oci_license_manager_configuration.export_configuration.id
    source {
      category = "vcn"
      parameters = {
        "capture_filter"      = oci_core_capture_filter.export_Teste_FNET_US_TO_SP.id
        "enablementPointType" = "VCN"
      }
      resource    = oci_core_vcn.export_VCN_172-28_SANDBOX.id
      service     = "flowlogs"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2024-03-07T14:48:42.697Z"
  }
  display_name = "Teste-Fnet_1"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Fnet_SP.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_sandbox_mp_mc_error {
  configuration {
    compartment_id = oci_license_manager_configuration.export_configuration.id
    source {
      category = "error"
      parameters = {
      }
      resource    = oci_load_balancer_load_balancer.export_sandbox-mp-mc.id
      service     = "loadbalancer"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T17:19:16.177Z"
  }
  display_name = "sandbox_mp_mc_error"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_sandbox-mp-mc_1.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_sandbox_mp_mc_access {
  configuration {
    compartment_id = oci_license_manager_configuration.export_configuration.id
    source {
      category = "access"
      parameters = {
      }
      resource    = oci_load_balancer_load_balancer.export_sandbox-mp-mc.id
      service     = "loadbalancer"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/marcelo.quintas@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-12-19T17:19:10.211Z"
  }
  display_name = "sandbox_mp_mc_access"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_sandbox-mp-mc_1.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_britech-2_2 {
  configuration {
    compartment_id = oci_license_manager_configuration.export_configuration.id
    source {
      category = "vnic"
      parameters = {
        "capture_filter"      = oci_core_capture_filter.export_britech-capture-2.id
        "enablementPointType" = "VNIC OCID"
      }
      resource    = "ocid1.vnic.oc1.iad.abuwcljsrmxizrxv2hrzqsye3ncnjvemz3hmlxe4kr7tkckx7ocsvfu7kjwa"
      service     = "flowlogs"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2023-11-24T13:59:22.794Z"
  }
  display_name = "britech-2_2"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_britech-teste.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_britech-2_1 {
  configuration {
    compartment_id = oci_license_manager_configuration.export_configuration.id
    source {
      category = "subnet"
      parameters = {
        "capture_filter"      = oci_core_capture_filter.export_britech-capture-2.id
        "enablementPointType" = "Subnet"
      }
      resource    = oci_core_subnet.export_SUB_HML_PRIV_ASHBURN_04.id
      service     = "flowlogs"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2023-11-24T13:59:22.616Z"
  }
  display_name = "britech-2_1"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_britech-teste.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_britech-logs_1 {
  configuration {
    compartment_id = oci_license_manager_configuration.export_configuration.id
    source {
      category = "vnic"
      parameters = {
        "capture_filter"      = oci_core_capture_filter.export_britech-teste-cap-filter.id
        "enablementPointType" = "VNIC OCID"
      }
      resource    = "ocid1.vnic.oc1.iad.abuwcljsyo23is5x4un4ozoeoujfptkxwbq3pmema2xt7kiudywntlrw3hka"
      service     = "flowlogs"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/luiz.paiva@orama.com.br"
    "Oracle-Tags.CreatedOn" = "2023-11-23T19:36:03.741Z"
  }
  display_name = "britech-logs_1"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_britech-teste.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

