## This configuration was generated by terraform-provider-oci

resource oci_marketplace_accepted_agreement export_acceptedAgreement-piiocid1-user-oc1-aaaaaaaanlqeot3rurd3e4ewphudba2cqocdrocsk5lm3zbluxqmpvbfsrka {
  agreement_id   = "pii"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  display_name = "acceptedAgreement-piiocid1.user.oc1..aaaaaaaanlqeot3rurd3e4ewphudba2cqocdrocsk5lm3zbluxqmpvbfsrka"
  freeform_tags = {
  }
  listing_id      = "67830324"
  package_version = "AS 2.11.3"
  signature       = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [signature]
  }
}

resource oci_marketplace_accepted_agreement export_acceptedAgreement-143493954ocid1-user-oc1-aaaaaaaanlqeot3rurd3e4ewphudba2cqocdrocsk5lm3zbluxqmpvbfsrka {
  agreement_id   = "143493954"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  display_name = "acceptedAgreement-143493954ocid1.user.oc1..aaaaaaaanlqeot3rurd3e4ewphudba2cqocdrocsk5lm3zbluxqmpvbfsrka"
  freeform_tags = {
  }
  listing_id      = "67830324"
  package_version = "AS 2.11.3"
  signature       = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [signature]
  }
}

resource oci_marketplace_accepted_agreement export_acceptedAgreement-149661806ocid1-user-oc1-aaaaaaaanlqeot3rurd3e4ewphudba2cqocdrocsk5lm3zbluxqmpvbfsrka {
  agreement_id   = "149661806"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  display_name = "acceptedAgreement-149661806ocid1.user.oc1..aaaaaaaanlqeot3rurd3e4ewphudba2cqocdrocsk5lm3zbluxqmpvbfsrka"
  freeform_tags = {
  }
  listing_id      = "67830324"
  package_version = "AS 2.11.3"
  signature       = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [signature]
  }
}

resource oci_marketplace_accepted_agreement export_acceptedAgreement-38361109ocid1-user-oc1-aaaaaaaani6tdbmpvr3k3lj2hb7vyxdxcds4tta6f3sdicvyiqecqugvzquq {
  agreement_id   = "38361109"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  display_name = "acceptedAgreement-38361109ocid1.user.oc1..aaaaaaaani6tdbmpvr3k3lj2hb7vyxdxcds4tta6f3sdicvyiqecqugvzquq"
  freeform_tags = {
  }
  listing_id      = "60923152"
  package_version = "Microsoft SQL 2019 Standard 15.0.4053.23"
  signature       = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [signature]
  }
}

