## This configuration was generated by terraform-provider-oci

resource oci_mysql_mysql_backup export_Final-Backup---mysql-sandbox-03b {
  backup_type    = "FULL"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  db_system_id   = "ocid1.mysqldbsystem.oc1.iad.aaaaaaaa4ix55ccdtu3ginquw4fovjxuyoozuscqozk6q5pbqy2myeuuhnaq"
  #db_system_snapshot_summary = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-18T21:36:26.056Z"
  }
  #description = <<Optional value not found in discovery>>
  display_name = "Final Backup - mysql-sandbox-03b"
  freeform_tags = {
    "Template" = "Development or testing"
  }
  retention_in_days = "365"
  #source_details = <<Optional value not found in discovery>>
}

resource oci_mysql_mysql_backup export_Final-Backup---mysql-sandbox-03c {
  backup_type    = "FULL"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  db_system_id   = "ocid1.mysqldbsystem.oc1.iad.aaaaaaaaeeftvdkfj24usnrsheipvblgidkqbpeshwkfjucxclgjorite6sa"
  #db_system_snapshot_summary = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-10-18T21:37:11.083Z"
  }
  #description = <<Optional value not found in discovery>>
  display_name = "Final Backup - mysql-sandbox-03c"
  freeform_tags = {
    "Template" = "Development or testing"
  }
  retention_in_days = "365"
  #source_details = <<Optional value not found in discovery>>
}

resource oci_mysql_mysql_configuration export_MinhaConta-CustomConfigurations {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/suporte@perseustech.dev"
    "Oracle-Tags.CreatedOn" = "2023-11-06T19:00:58.714Z"
  }
  description  = "Default standalone configuration for the MySQL.VM.Standard.E4.4.64GB MySQL shape"
  display_name = "MinhaConta-CustomConfigurations"
  freeform_tags = {
  }
  init_variables {
    lower_case_table_names = "CASE_SENSITIVE"
  }
  parent_configuration_id = "ocid1.mysqlconfiguration.oc1..aaaaaaaauxn6tddkgan34ikhv4jxi7ygdjucqrj7tpcpnzhxx7ywte33pxya"
  shape_name              = "MySQL.VM.Standard.E4.4.64GB"
  variables {
    #autocommit = <<Optional value not found in discovery>>
    #big_tables = <<Optional value not found in discovery>>
    binlog_expire_logs_seconds = "3600"
    binlog_row_metadata        = ""
    binlog_row_value_options   = "PARTIAL_JSON"
    #binlog_transaction_compression = <<Optional value not found in discovery>>
    completion_type = ""
    #connect_timeout = <<Optional value not found in discovery>>
    #connection_memory_chunk_size = <<Optional value not found in discovery>>
    #connection_memory_limit = <<Optional value not found in discovery>>
    #cte_max_recursion_depth = <<Optional value not found in discovery>>
    default_authentication_plugin = "mysql_native_password"
    #foreign_key_checks = <<Optional value not found in discovery>>
    #global_connection_memory_limit = <<Optional value not found in discovery>>
    #global_connection_memory_tracking = <<Optional value not found in discovery>>
    group_replication_consistency = "BEFORE_ON_PRIMARY_FAILOVER"
    #information_schema_stats_expiry = <<Optional value not found in discovery>>
    #innodb_buffer_pool_dump_pct = <<Optional value not found in discovery>>
    innodb_buffer_pool_instances = "4"
    innodb_buffer_pool_size      = "51539607552"
    #innodb_ddl_buffer_size = <<Optional value not found in discovery>>
    #innodb_ddl_threads = <<Optional value not found in discovery>>
    #innodb_ft_enable_stopword = <<Optional value not found in discovery>>
    #innodb_ft_max_token_size = <<Optional value not found in discovery>>
    #innodb_ft_min_token_size = <<Optional value not found in discovery>>
    #innodb_ft_num_word_optimize = <<Optional value not found in discovery>>
    innodb_ft_result_cache_limit = "33554432"
    #innodb_ft_server_stopword_table = <<Optional value not found in discovery>>
    #innodb_lock_wait_timeout = <<Optional value not found in discovery>>
    #innodb_log_writer_threads = <<Optional value not found in discovery>>
    #innodb_max_purge_lag = <<Optional value not found in discovery>>
    innodb_max_purge_lag_delay = "300000"
    #innodb_stats_persistent_sample_pages = <<Optional value not found in discovery>>
    #innodb_stats_transient_sample_pages = <<Optional value not found in discovery>>
    #interactive_timeout = <<Optional value not found in discovery>>
    local_infile    = "true"
    mandatory_roles = "public"
    #max_allowed_packet = <<Optional value not found in discovery>>
    max_binlog_cache_size = "4294967296"
    #max_connect_errors = <<Optional value not found in discovery>>
    max_connections = "4000"
    #max_execution_time = <<Optional value not found in discovery>>
    #max_heap_table_size = <<Optional value not found in discovery>>
    #max_prepared_stmt_count = <<Optional value not found in discovery>>
    #mysql_firewall_mode = <<Optional value not found in discovery>>
    #mysqlx_connect_timeout = <<Optional value not found in discovery>>
    #mysqlx_deflate_default_compression_level = <<Optional value not found in discovery>>
    #mysqlx_deflate_max_client_compression_level = <<Optional value not found in discovery>>
    #mysqlx_enable_hello_notice = <<Optional value not found in discovery>>
    #mysqlx_interactive_timeout = <<Optional value not found in discovery>>
    #mysqlx_lz4default_compression_level = <<Optional value not found in discovery>>
    #mysqlx_lz4max_client_compression_level = <<Optional value not found in discovery>>
    #mysqlx_max_allowed_packet = <<Optional value not found in discovery>>
    #mysqlx_read_timeout = <<Optional value not found in discovery>>
    #mysqlx_wait_timeout = <<Optional value not found in discovery>>
    #mysqlx_write_timeout = <<Optional value not found in discovery>>
    #mysqlx_zstd_default_compression_level = <<Optional value not found in discovery>>
    #mysqlx_zstd_max_client_compression_level = <<Optional value not found in discovery>>
    #net_read_timeout = <<Optional value not found in discovery>>
    #net_write_timeout = <<Optional value not found in discovery>>
    #parser_max_mem_size = <<Optional value not found in discovery>>
    #regexp_time_limit = <<Optional value not found in discovery>>
    #sort_buffer_size = <<Optional value not found in discovery>>
    sql_mode = "ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES"
    #sql_require_primary_key = <<Optional value not found in discovery>>
    #sql_warnings = <<Optional value not found in discovery>>
    #thread_pool_dedicated_listeners = <<Optional value not found in discovery>>
    #thread_pool_max_transactions_limit = <<Optional value not found in discovery>>
    time_zone = "UTC"
    #tmp_table_size = <<Optional value not found in discovery>>
    transaction_isolation = ""
    #wait_timeout = <<Optional value not found in discovery>>
  }
}

